loom.serverOnlyMinecraftJar()

configurations {
    versionAdapterShadow
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"

    compileOnly 'org.jetbrains:annotations:26.1.0'
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    compileOnly 'org.slf4j:slf4j-api:2.0.17'
    compileOnly files(project(':fabricUniversal').sourceSets.main.output)
}

tasks.compileJava.dependsOn(project(':fabricUniversal').tasks.named('classes'))

jar {
    destinationDirectory.set(file("$projectDir/build/libs"))
}

shadowJar {
    configurations = [project.configurations.versionAdapterShadow]
    archiveClassifier.set('dev-shadow')
    destinationDirectory.set(file("$projectDir/build/libs"))
}

remapJar {
    dependsOn tasks.jar
    mustRunAfter tasks.jar
    inputFile = jar.archiveFile.get()

    destinationDirectory.set(file("$projectDir/build/libs"))
    archiveClassifier.set('')
}

jar.finalizedBy(remapJar)
